name: React CI - Build & Push

on:
  push:
    branches: ["develop", "qa", "uat", "main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Docker login
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 3️⃣ Build & Push image
      - name: Build & Push Docker Image
        run: |
          SHA=$(git rev-parse --short HEAD)
          IMAGE=adenli/media-node

          docker build -t $IMAGE:$SHA .
          docker push $IMAGE:$SHA

          echo "IMAGE_TAG=$SHA" >> $GITHUB_ENV

      # 4️⃣ Output info
      - name: Print image info
        run: |
          echo "Built image: adenli/media-node:${IMAGE_TAG}"